In [8]:
import pandas as pd
from datetime import datetime

In [9]:
df=pd.read_csv('crime_2011_9_chicago.csv')

In [10]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'Unnamed: 0.1.1', 'ID', 'Case Number',
       'DateTime', 'Block', 'IUCR', 'Primary Type', 'Description',
       'Location Description', 'Arrest', 'Domestic', 'Beat', 'District',
       'Ward', 'Community Area', 'FBI Code', 'X Coordinate', 'Y Coordinate',
       'Year', 'Updated On', 'Latitude', 'Longitude', 'Location', 'date',
       'Date', 'Time', 'Hour'],
      dtype='object')

In [4]:
df=df.rename_axis({'Date':'DateTime'},axis="columns")

In [15]:
df

,Unnamed: 0,Unnamed: 0.1,ID,Case Number,DateTime,Block,IUCR,Primary Type,Description,Location Description,...,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,date,Date,Time,Hour
0,0,74492,8288016,HT521849,2011-09-30 04:00:00,005XX N STATE ST,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,APARTMENT,...,NaN,2011,04/15/2016 11:16:05 AM,NaN,NaN,NaN,2011-09-30 04:00:00,2011-09-30,04:00:00,4
1,1,110847,8245376,HT478840,2011-09-02 23:45:00,004XX W GOETHE ST,0820,THEFT,$500 AND UNDER,STREET,...,NaN,2011,08/17/2015 03:03:40 PM,NaN,NaN,NaN,2011-09-02 23:45:00,2011-09-02,23:45:00,23
2,2,110848,8246563,HT480557,2011-09-04 02:45:00,087XX S WOOD ST,0460,BATTERY,SIMPLE,STREET,...,1846684.0,2011,02/04/2016 06:33:39 AM,41.734881,-87.667909,"(41.734881215, -87.667909418)",2011-09-04 02:45:00,2011-09-04,02:45:00,2
3,3,110849,8247469,HT480488,2011-09-04 01:00:00,041XX W 50TH ST,1020,ARSON,BY FIRE,STREET,...,1871147.0,2011,02/04/2016 06:33:39 AM,41.802341,-87.726734,"(41.80234067, -87.72673419)",2011-09-04 01:00:00,2011-09-04,01:00:00,1
4,4,110850,8247647,HT481860,2011-09-05 00:56:00,017XX W 77TH ST,031A,ROBBERY,ARMED: HANDGUN,ALLEY,...,1853639.0,2011,02/04/2016 06:33:39 AM,41.753958,-87.666261,"(41.75395833, -87.666261113)",2011-09-05 00:56:00,2011-09-05,00:56:00,0
5,5,110858,8250072,HT484059,2011-09-06 15:00:00,022XX W 69TH ST,0820,THEFT,$500 AND UNDER,OTHER,...,1858868.0,2011,02/04/2016 06:33:39 AM,41.768381,-87.678945,"(41.76838123, -87.678945374)",2011-09-06 15:00:00,2011-09-06,15:00:00,15
6,6,110862,8254336,HT484881,2011-09-02 07:30:00,055XX S Parkside ave,0820,THEFT,$500 AND UNDER,NaN,...,NaN,2011,08/17/2015 03:03:40 PM,NaN,NaN,NaN,2011-09-02 07:30:00,2011-09-02,07:30:00,7
7,7,110867,8255366,HT489135,2011-09-09 18:00:00,059XX W LAKE ST,0560,ASSAULT,SIMPLE,STREET,...,1902268.0,2011,02/04/2016 06:33:39 AM,41.887983,-87.773613,"(41.887983008, -87.773612707)",2011-09-09 18:00:00,2011-09-09,18:00:00,18
8,8,110882,8263301,HT496794,2011-09-14 15:40:00,043XX W 21ST PL,0460,BATTERY,SIMPLE,SIDEWALK,...,1889403.0,2011,02/04/2016 06:33:39 AM,41.852473,-87.732978,"(41.852472938, -87.732977791)",2011-09-14 15:40:00,2011-09-14,15:40:00,15
9,9,110888,8265753,HT499137,2011-09-14 14:30:00,020XX E 79TH ST,0870,THEFT,POCKET-PICKING,CTA BUS,...,1852988.0,2011,02/04/2016 06:33:39 AM,41.751610,-87.575678,"(41.751610161, -87.57567807)",2011-09-14 14:30:00,2011-09-14,14:30:00,14
10,10,110892,8266314,HT499669,2011-09-03 09:15:00,034XX W 38TH ST,0810,THEFT,OVER $500,RESIDENCE,...,1879185.0,2011,02/04/2016 06:33:39 AM,41.824313,-87.710593,"(41.82431282, -87.710592783)",2011-09-03 09:15:00,2011-09-03,09:15:00,9
11,11,110914,8272925,HT506987,2011-09-21 06:15:00,083XX S INGLESIDE AVE,0560,ASSAULT,SIMPLE,STREET,...,1849952.0,2011,02/04/2016 06:33:39 AM,41.743445,-87.601373,"(41.743445022, -87.60137277)",2011-09-21 06:15:00,2011-09-21,06:15:00,6
12,12,110919,8273792,HT508121,2011-09-21 22:15:00,012XX W 76TH ST,0460,BATTERY,SIMPLE,SIDEWALK,...,1854428.0,2011,02/04/2016 06:33:39 AM,41.756057,-87.654929,"(41.756057234, -87.654929158)",2011-09-21 22:15:00,2011-09-21,22:15:00,22
13,13,110928,8276233,HT510303,2011-09-23 09:45:00,002XX S STATE ST,0560,ASSAULT,SIMPLE,CTA BUS,...,1899396.0,2011,02/04/2016 06:33:39 AM,41.879298,-87.627706,"(41.879297705, -87.627706271)",2011-09-23 09:45:00,2011-09-23,09:45:00,9
14,14,110930,8277085,HT511273,2011-09-23 21:35:00,008XX N STATE ST,0460,BATTERY,SIMPLE,SIDEWALK,...,1905805.0,2011,02/04/2016 06:33:39 AM,41.896889,-87.628203,"(41.896888586, -87.628203192)",2011-09-23 21:35:00,2011-09-23,21:35:00,21
15,15,110943,8281441,HT514836,2011-09-25 08:50:00,111XX S Avenue G,0890,THEFT,FROM BUILDING,NaN,...,NaN,2011,08/17/2015 03:03:40 PM,NaN,NaN,NaN,2011-09-25 08:50:00,2011-09-25,08:50:00,8
16,16,110958,8287272,HT521308,2011-09-30 13:00:00,028XX N BROADWAY,0810,THEFT,OVER $500,STREET,...,1919218.0,2011,02/04/2016 06:33:39 AM,41.933796,-87.644548,"(41.933796108, -87.644548217)",2011-09-30 13:00:00,2011-09-30,13:00:00,13
17,17,110965,8290973,HT513280,2011-09-25 08:45:00,0000X S CICERO AVE,0460,BATTERY,SIMPLE,STREET,...,1899501.0,2011,02/04/2016 06:33:39 AM,41.880248,-87.745269,"(41.88024803, -87.745269129)",2011-09-25 08:45:00,2011-09-25,08:45:00,8
18,18,114324,9559519,HX210794,2011-09-30 00:01:00,027XX N RIDGEWAY AVE,0266,CRIM SEXUAL ASSAULT,PREDATORY,RESIDENCE,...,NaN,2011,08/17/2015 03:03:40 PM,NaN,NaN,NaN,2011-09-30 00:01:00,2011-09-30,00:01:00,0
19,19,114740,9585596,HX235722,2011-09-02 00:01:00,094XX S PRAIRIE AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,...,NaN,2011,08/17/2015 03:03:40 PM,NaN,NaN,NaN,2011-09-02 00:01:00,2011-09-02,00:01:00,0
20,20,114818,9589846,HT498337,2011-09-15 16:11:00,039XX W THOMAS ST,2014,NARCOTICS,MANU/DELIVER: HEROIN (WHITE),SIDEWALK,...,NaN,2011,08/17/2015 03:03:40 PM,NaN,NaN,NaN,2011-09-15 16:11:00,2011-09-15,16:11:00,16
21,21,115707,9651885,HX301799,2011-09-01 00:00:00,092XX S NORMAL AVE,1154,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT $300 AND UNDER,RESIDENCE,...,NaN,2011,08/17/2015 03:03:40 PM,NaN,NaN,NaN,2011-09-01 00:00:00,2011-09-01,00:00:00,0
22,22,116001,9673084,HX323080,2011-09-14 00:01:00,006XX S DEARBORN ST,5001,OTHER OFFENSE,OTHER CRIME INVOLVING PROPERTY,OTHER,...,NaN,2011,08/17/2015 03:03:40 PM,NaN,NaN,NaN,2011-09-14 00:01:00,2011-09-14,00:01:00,0
23,23,116217,9686416,HX336870,2011-09-26 12:00:00,048XX N KEYSTONE AVE,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,OTHER,...,NaN,2011,08/17/2015 03:03:40 PM,NaN,NaN,NaN,2011-09-26 12:00:00,2011-09-26,12:00:00,12
24,24,116257,9691011,HX340588,2011-09-16 16:00:00,013XX S SPRINGFIELD AVE,1562,SEX OFFENSE,AGG CRIMINAL SEXUAL ABUSE,APARTMENT,...,NaN,2011,08/17/2015 03:03:40 PM,NaN,NaN,NaN,2011-09-16 16:00:00,2011-09-16,16:00:00,16
25,25,116511,9708919,HX358684,2011-09-01 00:00:00,032XX W DOUGLAS BLVD,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,OTHER,...,NaN,2011,08/17/2015 03:03:40 PM,NaN,NaN,NaN,2011-09-01 00:00:00,2011-09-01,00:00:00,0
26,26,116536,9712064,HX362288,2011-09-22 00:01:00,070XX S NORMAL BLVD,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,...,NaN,2011,08/17/2015 03:03:40 PM,NaN,NaN,NaN,2011-09-22 00:01:00,2011-09-22,00:01:00,0
27,27,116607,9716556,HX366578,2011-09-15 12:00:00,048XX W WRIGHTWOOD AVE,1563,SEX OFFENSE,CRIMINAL SEXUAL ABUSE,RESIDENCE,...,NaN,2011,08/17/2015 03:03:40 PM,NaN,NaN,NaN,2011-09-15 12:00:00,2011-09-15,12:00:00,12
28,28,117237,9765134,HX413533,2011-09-03 09:00:00,017XX N KEDZIE AVE,1154,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT $300 AND UNDER,RESIDENCE,...,NaN,2011,08/17/2015 03:03:40 PM,NaN,NaN,NaN,2011-09-03 09:00:00,2011-09-03,09:00:00,9
29,29,117679,9793833,HX442566,2011-09-25 05:00:00,018XX S HARDING AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,...,NaN,2011,08/17/2015 03:03:40 PM,NaN,NaN,NaN,2011-09-25 05:00:00,2011-09-25,05:00:00,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29886,29886,3374936,20075,HT464142,2011-09-23 06:07:00,051XX W BLOOMINGDALE AVE,0110,HOMICIDE,FIRST DEGREE MURDER,ALLEY,...,1911484.0,2011,08/17/2015 03:03:40 PM,41.913178,-87.754181,"(41.913177577, -87.754181327)",2011-09-23 06:07:00,2011-09-23,06:07:00,6
29887,29887,3375081,20077,HT514961,2011-09-26 12:45:00,046XX S LANGLEY AVE,0110,HOMICIDE,FIRST DEGREE MURDER,HALLWAY,...,1874420.0,2011,08/17/2015 03:03:40 PM,41.810641,-87.609012,"(41.810640725, -87.609011934)",2011-09-26 12:45:00,2011-09-26,12:45:00,12
29888,29888,3375161,20078,HT515262,2011-09-26 16:12:00,004XX E 60TH ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,...,1865323.0,2011,08/17/2015 03:03:40 PM,41.785714,-87.615064,"(41.785714007, -87.615063951)",2011-09-26 16:12:00,2011-09-26,16:12:00,16
29889,29889,3375251,20079,HT513786,2011-09-26 02:05:00,007XX N SPRINGFIELD AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,...,1904668.0,2011,08/17/2015 03:03:40 PM,41.894315,-87.723606,"(41.894314571, -87.72360584)",2011-09-26 02:05:00,2011-09-26,02:05:00,2
29890,29890,3375339,20080,HT518983,2011-09-28 22:07:00,012XX E 94TH ST,0110,HOMICIDE,FIRST DEGREE MURDER,AUTO,...,1842914.0,2011,08/17/2015 03:03:40 PM,41.724079,-87.593292,"(41.724078808, -87.593291837)",2011-09-28 22:07:00,2011-09-28,22:07:00,22
29891,29891,3383948,20189,Y449586,2011-09-10 14:40:00,036XX W CHICAGO AVE,0110,HOMICIDE,FIRST DEGREE MURDER,CTA BUS,...,1905090.0,2011,08/17/2015 03:03:40 PM,41.895443,-87.718089,"(41.895443218, -87.718089317)",2011-09-10 14:40:00,2011-09-10,14:40:00,14
29892,29892,4197018,10505473,HZ246932,2011-09-26 08:00:00,001XX E 104TH PL,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,OTHER,...,NaN,2011,05/02/2016 03:52:24 PM,NaN,NaN,NaN,2011-09-26 08:00:00,2011-09-26,08:00:00,8
29893,29893,4473518,8260127,HT494217,2011-09-12 23:45:00,036XX W FIFTH AVE,1811,NARCOTICS,POSS: CANNABIS 30GMS OR LESS,STREET,...,NaN,2011,05/04/2016 03:48:23 PM,NaN,NaN,NaN,2011-09-12 23:45:00,2011-09-12,23:45:00,23
29894,29894,4473540,8275200,HT509264,2011-09-22 16:20:00,009XX E 58TH ST,2093,NARCOTICS,FOUND SUSPECT NARCOTICS,HOSPITAL BUILDING/GROUNDS,...,NaN,2011,05/04/2016 03:48:23 PM,NaN,NaN,NaN,2011-09-22 16:20:00,2011-09-22,16:20:00,16
29895,29895,4473562,8287737,HT521608,2011-09-30 15:13:00,018XX N ST LOUIS AVE,1811,NARCOTICS,POSS: CANNABIS 30GMS OR LESS,SIDEWALK,...,NaN,2011,05/04/2016 03:48:23 PM,NaN,NaN,NaN,2011-09-30 15:13:00,2011-09-30,15:13:00,15
29896,29896,5340713,10648109,HZ398766,2011-09-21 00:00:00,044XX S WELLS ST,1154,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT $300 AND UNDER,APARTMENT,...,NaN,2011,08/20/2016 03:54:24 PM,NaN,NaN,NaN,2011-09-21 00:00:00,2011-09-21,00:00:00,0
29897,29897,5348825,8250688,HT484837,2011-09-07 00:30:00,078XX S PEORIA ST,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,OTHER,...,1852808.0,2011,07/13/2016 03:47:55 PM,41.751561,-87.646493,"(41.751561338, -87.646492597)",2011-09-07 00:30:00,2011-09-07,00:30:00,0
29898,29898,5350955,10569087,HZ317074,2011-09-30 23:00:00,072XX S CHAMPLAIN AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,...,NaN,2011,06/22/2016 03:52:12 PM,NaN,NaN,NaN,2011-09-30 23:00:00,2011-09-30,23:00:00,23
29899,29899,5368038,10593674,HZ344948,2011-09-22 00:00:00,076XX S PAULINA ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,OTHER,...,NaN,2011,07/12/2016 03:53:40 PM,NaN,NaN,NaN,2011-09-22 00:00:00,2011-09-22,00:00:00,0
29900,29900,5374468,10603948,HZ355675,2011-09-06 00:00:00,063XX S GREENWOOD AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,...,NaN,2011,07/20/2016 03:52:04 PM,NaN,NaN,NaN,2011-09-06 00:00:00,2011-09-06,00:00:00,0
29901,29901,5401847,10654277,HZ403517,2011-09-23 16:00:00,055XX S EVERETT AVE,1154,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT $300 AND UNDER,NaN,...,NaN,2011,08/24/2016 03:50:52 PM,NaN,NaN,NaN,2011-09-23 16:00:00,2011-09-23,16:00:00,16
29902,29902,5412631,10670134,HZ421827,2011-09-03 22:30:00,078XX S VINCENNES AVE,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,SMALL RETAIL STORE,...,NaN,2011,09/06/2016 03:55:40 PM,NaN,NaN,NaN,2011-09-03 22:30:00,2011-09-03,22:30:00,22
29903,29903,5452013,10729798,HZ489188,2011-09-01 00:00:00,069XX S PEORIA ST,1565,SEX OFFENSE,INDECENT SOLICITATION/CHILD,APARTMENT,...,NaN,2011,10/26/2016 03:50:11 PM,NaN,NaN,NaN,2011-09-01 00:00:00,2011-09-01,00:00:00,0
29904,29904,5475808,8310057,HT514006,2011-09-03 12:00:00,044XX S SHIELDS AVE,0265,CRIM SEXUAL ASSAULT,AGGRAVATED: OTHER,RESIDENCE,...,1875282.0,2011,11/27/2016 03:45:20 PM,41.813165,-87.634621,"(41.813164917, -87.634620968)",2011-09-03 12:00:00,2011-09-03,12:00:00,12
29905,29905,5484100,10777957,HZ544388,2011-09-18 22:00:00,002XX N STATE ST,1564,SEX OFFENSE,CRIMINAL TRANSMISSION OF HIV,HOTEL/MOTEL,...,NaN,2011,12/09/2016 03:49:50 PM,NaN,NaN,NaN,2011-09-18 22:00:00,2011-09-18,22:00:00,22
29906,29906,5505180,10819211,HZ570598,2011-09-01 00:01:00,056XX S MICHIGAN AVE,0266,CRIM SEXUAL ASSAULT,PREDATORY,RESIDENCE,...,NaN,2011,08/26/2017 03:51:03 PM,NaN,NaN,NaN,2011-09-01 00:01:00,2011-09-01,00:01:00,0
29907,29907,5506204,8277882,HT512185,2011-09-24 13:51:00,038XX W MADISON ST,041A,BATTERY,AGGRAVATED: HANDGUN,VEHICLE NON-COMMERCIAL,...,1899736.0,2011,03/02/2017 03:52:34 PM,41.880772,-87.722093,"(41.880771913, -87.722093159)",2011-09-24 13:51:00,2011-09-24,13:51:00,13
29908,29908,5544131,10868082,JA174017,2011-09-28 12:00:00,003XX N STATE ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,...,NaN,2011,03/05/2017 03:50:44 PM,NaN,NaN,NaN,2011-09-28 12:00:00,2011-09-28,12:00:00,12
29909,29909,5585633,10932757,JA248656,2011-09-09 00:01:00,005XX W MADISON ST,1140,DECEPTIVE PRACTICE,EMBEZZLEMENT,BANK,...,NaN,2011,05/03/2017 03:53:47 PM,NaN,NaN,NaN,2011-09-09 00:01:00,2011-09-09,00:01:00,0
29910,29910,5625921,10992586,JA319320,2011-09-07 08:00:00,001XX N LAVERGNE AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,...,NaN,2011,06/24/2017 03:50:57 PM,NaN,NaN,NaN,2011-09-07 08:00:00,2011-09-07,08:00:00,8
29911,29911,5668274,11054841,JA391636,2011-09-14 09:00:00,061XX S KIMBARK AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,...,NaN,2011,08/15/2017 03:58:56 PM,NaN,NaN,NaN,2011-09-14 09:00:00,2011-09-14,09:00:00,9
29912,29912,5678062,11067825,JA406739,2011-09-14 00:01:00,074XX W BELMONT AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,...,NaN,2011,08/27/2017 03:48:51 PM,NaN,NaN,NaN,2011-09-14 00:01:00,2011-09-14,00:01:00,0
29913,29913,5688380,11080614,JA422777,2011-09-26 10:00:00,070XX S CRANDON AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,...,NaN,2011,09/08/2017 03:48:38 PM,NaN,NaN,NaN,2011-09-26 10:00:00,2011-09-26,10:00:00,10
29914,29914,5703680,11103112,JA450748,2011-09-01 00:00:00,009XX W LAKESIDE PL,1751,OFFENSE INVOLVING CHILDREN,CRIM SEX ABUSE BY FAM MEMBER,RESIDENCE,...,NaN,2011,09/29/2017 03:49:32 PM,NaN,NaN,NaN,2011-09-01 00:00:00,2011-09-01,00:00:00,0
29915,29915,5712550,8261801,HT495672,2011-09-13 21:17:00,029XX W BLOOMINGDALE AVE,0430,BATTERY,AGGRAVATED: OTHER DANG WEAPON,STREET,...,1911860.0,2011,10/11/2017 03:48:43 PM,41.913927,-87.700706,"(41.913927246, -87.700706336)",2011-09-13 21:17:00,2011-09-13,21:17:00,21

In [6]:
df["DateTime"] = df["DateTime"].apply(lambda x:datetime.strptime(x,"%m/%d/%Y %I:%M:%S %p"))

TypeError: ('strptime() argument 1 must be str, not Series', 'occurred at index DateTime')

In [63]:
df['Date']=[d.date() for d in df['DateTime']]
df['Time']=[d.time() for d in df['DateTime']]

In [64]:
df['Hour']=df['DateTime'].dt.hour

In [11]:
df['DateTime'].rename_axis('Date',axis=1)

Date              DateTime    DateTime
0      2011-09-30 04:00:00  2011-09-30
1      2011-09-02 23:45:00  2011-09-02
2      2011-09-04 02:45:00  2011-09-04
3      2011-09-04 01:00:00  2011-09-04
4      2011-09-05 00:56:00  2011-09-05
5      2011-09-06 15:00:00  2011-09-06
6      2011-09-02 07:30:00  2011-09-02
7      2011-09-09 18:00:00  2011-09-09
8      2011-09-14 15:40:00  2011-09-14
9      2011-09-14 14:30:00  2011-09-14
10     2011-09-03 09:15:00  2011-09-03
11     2011-09-21 06:15:00  2011-09-21
12     2011-09-21 22:15:00  2011-09-21
13     2011-09-23 09:45:00  2011-09-23
14     2011-09-23 21:35:00  2011-09-23
15     2011-09-25 08:50:00  2011-09-25
16     2011-09-30 13:00:00  2011-09-30
17     2011-09-25 08:45:00  2011-09-25
18     2011-09-30 00:01:00  2011-09-30
19     2011-09-02 00:01:00  2011-09-02
20     2011-09-15 16:11:00  2011-09-15
21     2011-09-01 00:00:00  2011-09-01
22     2011-09-14 00:01:00  2011-09-14
23     2011-09-26 12:00:00  2011-09-26
24     2011-09-16 16:00:00  2011-09-16
25     2011-09-01 00:00:00  2011-09-01
26     2011-09-22 00:01:00  2011-09-22
27     2011-09-15 12:00:00  2011-09-15
28     2011-09-03 09:00:00  2011-09-03
29     2011-09-25 05:00:00  2011-09-25
...                    ...         ...
29886  2011-09-23 06:07:00  2011-09-23
29887  2011-09-26 12:45:00  2011-09-26
29888  2011-09-26 16:12:00  2011-09-26
29889  2011-09-26 02:05:00  2011-09-26
29890  2011-09-28 22:07:00  2011-09-28
29891  2011-09-10 14:40:00  2011-09-10
29892  2011-09-26 08:00:00  2011-09-26
29893  2011-09-12 23:45:00  2011-09-12
29894  2011-09-22 16:20:00  2011-09-22
29895  2011-09-30 15:13:00  2011-09-30
29896  2011-09-21 00:00:00  2011-09-21
29897  2011-09-07 00:30:00  2011-09-07
29898  2011-09-30 23:00:00  2011-09-30
29899  2011-09-22 00:00:00  2011-09-22
29900  2011-09-06 00:00:00  2011-09-06
29901  2011-09-23 16:00:00  2011-09-23
29902  2011-09-03 22:30:00  2011-09-03
29903  2011-09-01 00:00:00  2011-09-01
29904  2011-09-03 12:00:00  2011-09-03
29905  2011-09-18 22:00:00  2011-09-18
29906  2011-09-01 00:01:00  2011-09-01
29907  2011-09-24 13:51:00  2011-09-24
29908  2011-09-28 12:00:00  2011-09-28
29909  2011-09-09 00:01:00  2011-09-09
29910  2011-09-07 08:00:00  2011-09-07
29911  2011-09-14 09:00:00  2011-09-14
29912  2011-09-14 00:01:00  2011-09-14
29913  2011-09-26 10:00:00  2011-09-26
29914  2011-09-01 00:00:00  2011-09-01
29915  2011-09-13 21:17:00  2011-09-13

[29916 rows x 2 columns]

In [5]:
df=df.dropna(axis=0)

In [6]:
df.to_csv(r'crime_2011_9_Chicago.csv')

In [3]:
df1=df.groupby(['Date','Hour','Community Area','Primary Type'],as_index=False)['DateTime'].count()

In [4]:
for i in range(len(df1)):
    df1.loc[i,'Hour']=chr(ord('A')+df1.loc[i,'Hour'])

In [24]:
df1

           Date Hour  DateTime
0    2011-09-01    A       100
1    2011-09-01    B        26
2    2011-09-01    C        29
3    2011-09-01    D        19
4    2011-09-01    E        19
5    2011-09-01    F        11
6    2011-09-01    G        23
7    2011-09-01    H        27
8    2011-09-01    I        43
9    2011-09-01    J        93
10   2011-09-01    K        56
11   2011-09-01    L        50
12   2011-09-01    M        70
13   2011-09-01    N        59
14   2011-09-01    O        42
15   2011-09-01    P        54
16   2011-09-01    Q        63
17   2011-09-01    R        49
18   2011-09-01    S        65
19   2011-09-01    T        59
20   2011-09-01    U        49
21   2011-09-01    V        63
22   2011-09-01    W        57
23   2011-09-01    X        49
24   2011-09-02    A        54
25   2011-09-02    B        36
26   2011-09-02    C        38
27   2011-09-02    D        18
28   2011-09-02    E        11
29   2011-09-02    F         9
..          ...  ...       ...
690  2011-09-29    S        56
691  2011-09-29    T        46
692  2011-09-29    U        54
693  2011-09-29    V        63
694  2011-09-29    W        53
695  2011-09-29    X        53
696  2011-09-30    A        48
697  2011-09-30    B        21
698  2011-09-30    C        15
699  2011-09-30    D        13
700  2011-09-30    E        17
701  2011-09-30    F        10
702  2011-09-30    G        15
703  2011-09-30    H        25
704  2011-09-30    I        41
705  2011-09-30    J        48
706  2011-09-30    K        39
707  2011-09-30    L        42
708  2011-09-30    M        63
709  2011-09-30    N        50
710  2011-09-30    O        64
711  2011-09-30    P        70
712  2011-09-30    Q        62
713  2011-09-30    R        53
714  2011-09-30    S        52
715  2011-09-30    T        53
716  2011-09-30    U        64
717  2011-09-30    V        53
718  2011-09-30    W        50
719  2011-09-30    X        54

[720 rows x 3 columns]

In [5]:
df1.to_csv('Community.csv')

In [17]:
df['Date']=df['Date'].apply(lambda x:datetime.strptime(x,"%Y-%m-%d"))

In [18]:
df['Date'].dt.day

0         4
1         4
2         5
3         6
4         9
5        14
6        14
7         3
8        21
9        21
10       23
11       23
12       30
13       25
14        9
15        9
16        1
17        1
18        1
19        1
20        1
21        1
22        1
23        1
24        1
25        1
26        1
27        1
28        1
29        1
         ..
29785     8
29786    11
29787    11
29788    12
29789    13
29790    13
29791    13
29792    14
29793    14
29794    15
29795    15
29796    17
29797    18
29798    18
29799    18
29800    18
29801    19
29802    19
29803    22
29804    22
29805    23
29806    26
29807    26
29808    26
29809    28
29810    10
29811     7
29812     3
29813    24
29814    13
Name: Date, Length: 29815, dtype: int64